defaults: &defaults
  host: discourse.ywzq4o.0001.usw2.cache.amazonaws.com
  port: 6379
  password: 
  db: discourse

developmiit:
  uri: redis://localhost:6379
  host: localhost
  port: 6379
  password:
  db: 0
  cache_db: 2

profile:
  <<: *defaults

test:
  <<: *defaults
  db: 1

staging:
  <<: *defaults

production:
  <<: *defaults
