defaults: &defaults
  host: discourse.ywzq4o.0001.usw2.cache.amazonaws.com
  port: 6379
  password:
  db: 0

development:
  host: localhost
  port: 6379
  password:
  db: 0

profile:
  <<: *defaults

test:
  <<: *defaults
  db: 1

staging:
  <<: *defaults

production:
  <<: *defaults
