defaults: &defaults
  uri: redis://localhost:6379
  host: localhost
  port: 6379
  password:
  db: 0
  cache_db: 2

developmiit:
  uri: redis://localhost:6379
  host: localhost
  port: 6379
  password:
  db: 0
  cache_db: 2

profile:
  <<: *defaults

test:
  <<: *defaults
  db: 1

staging:
  <<: *defaults

production:
  <<: *defaults
